# The RAGFlow team do not actively maintain docker-compose-gpu.yml, so use them at your own risk. 
# Pull requests to improve it are welcome.
include:
  - ./docker-compose-base.yml

services:
  ragflow:
    depends_on:
      mysql:
        condition: service_healthy
    image: ${RAGFLOW_IMAGE}
    container_name: ragflow-server
    ports:
      - ${SVR_HTTP_PORT}:9380
      - 80:80
      - 443:443
    volumes:
      - ./ragflow-logs:/ragflow/logs
      - ./nginx/ragflow.conf:/etc/nginx/conf.d/ragflow.conf
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../api/apps/sdk/dify_retrieval.py:/ragflow/api/apps/sdk/dify_retrieval.py
      - ../api/apps/sdk/knowledge_grap.py:/ragflow/api/apps/sdk/knowledge_grap.py
      # - ../api/apps/sdk/doc.py:/ragflow/api/apps/sdk/doc.py
      # - ../api/apps/api_app.py:/ragflow/api/apps/api_app.py
      # - ../api/settings.py:/ragflow/api/settings.py
      # - ../rag/nlp/search.py:/ragflow/rag/nlp/search.py
      - ../rag/nlp/query.py:/ragflow/rag/nlp/query.py
      # - ../rag/app/tag.py:/ragflow/rag/app/tag.py
    env_file: .env
    environment:
      - TZ=${TIMEZONE}
      - HF_ENDPOINT=${HF_ENDPOINT}
      - MACOS=${MACOS}
      - MAX_CONCURRENT_TASKS=${MAX_CONCURRENT_TASKS} #并发解析任务数
    networks:
      - ragflow
    restart: on-failure
    # https://docs.docker.com/engine/daemon/prometheus/#create-a-prometheus-configuration
    # If you're using Docker Desktop, the --add-host flag is optional. This flag makes sure that the host's internal IP gets exposed to the Prometheus container.
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
